### ISSUE TITLE
Readme should describe how inline `imports` work

### ISSUE THREAD

**Issue by stefanpenner** [SparshithNR/doc-tester#8]
Specifically, they should explain that they abide by the node resolution algorithm, based on the doc file they are written in.

On that note, should we provide the accurate `__dirname` and `__filename` variables to these test files?

**Comment by mike-north** [comment]
In light of #14, I also need to understand how imports work when I'm passing the code as text directly. Seems like I may need to pass along the path of the file in question or something

**Comment by stefanpenner** [comment]
Here using doc-tester and ensuring the tests are run from the perspective of the consumer.

https://github.com/stefanpenner/doc-test-example

Specifically, I suspect doc-tester's current setup is misleading. Code examples typically want to be viewed from the perspective of the consumer, and thus the imports should usually not be relative and internal.

For example, rather then:

```
import add from './add';

add(4, 5) // equals: 9;
add(4, 5) // not-equals: 6;
add(2, 3) // throws;
```

A user of a library would prefer to see:

```js
import add from 'doc-tester-example'; // or w/e the external module API is

add(4, 5) // equals: 9;
add(4, 5) // not-equals: 6;
add(2, 3) // throws;
```

I've written a small script, likely one that should inspire an addition to doc-tester the above use case have less friction. Originally I assumed the needed setup wouldn't be confusing, but I am likely wrong about that.
